#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-trio
Version  : 1.0.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/ce/d0/28733595ea799318219e71905d4e42e168d0db2d4714842623df824a2277/sphinxcontrib-trio-1.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/d0/28733595ea799318219e71905d4e42e168d0db2d4714842623df824a2277/sphinxcontrib-trio-1.0.1.tar.gz
Summary  : Make Sphinx better at documenting Python functions and methods
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: sphinxcontrib-trio-license = %{version}-%{release}
Requires: sphinxcontrib-trio-python = %{version}-%{release}
Requires: sphinxcontrib-trio-python3 = %{version}-%{release}
Requires: Sphinx
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3

%description
sphinxcontrib-trio
==================
This sphinx extension helps you document Python code that uses
async/await, or abstract methods, or context managers, or generators,
or ... you get the idea. It works by making sphinx's regular
directives for documenting Python functions and methods smarter and
more powerful. The name is because it was originally written for the
`Trio <https://trio.readthedocs.io>`__ project, and I'm not very
creative. But don't be put off â there's nothing Trio- or
async-specific about this extension; any Python project can
benefit. (Though projects using async/await probably benefit the most,
since sphinx's built-in tools are especially inadequate in this case.)

%package license
Summary: license components for the sphinxcontrib-trio package.
Group: Default

%description license
license components for the sphinxcontrib-trio package.


%package python
Summary: python components for the sphinxcontrib-trio package.
Group: Default
Requires: sphinxcontrib-trio-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-trio package.


%package python3
Summary: python3 components for the sphinxcontrib-trio package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sphinxcontrib-trio package.


%prep
%setup -q -n sphinxcontrib-trio-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546873106
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-trio
cp LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/sphinxcontrib-trio/LICENSE.APACHE2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-trio/LICENSE.APACHE2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
